version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]

  server:
    build: ./server
    env_file:
      - ./server/.env.example
    depends_on: [ mongo ]
    ports: ["4000:4000"]

  auth-service:
    build: ./auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports: ["8080:8080"]

volumes:
  mongo_data:
